### ISSUE TITLE
Issue with Njsamine is calling the outerscope before beforeAll func

### ISSUE THREAD

**Issue by wangvnn** [fschwiet/DreamNJasmine#21]
According to this:
"The outer scope of each specification is ran once to discover what tests are defined, and then again once again for each contained test. Test code must not block if its directly within a describe(), given, or when() expression. Such code will cause test discovery to stall.

Unlike Jasmine or RSpec, in NJasmine each level of scope for a test runs for every test. If you really want some setup code to run once for multiple tests, use beforeAll(). The expression passed to beforeAll() is invoked once then any value it returns is passed to the following tests."

The outer scope (example given, when) can be called before 'beforeAll' function which can cause issue if the given's code depends on beforeAll code. I understand that I can turn on the flag in beforeAll and check it in given, when code... but this is not very friendly.

Any one has any suggestion?

**Comment by fschwiet** [comment]
An example might help, but generally whatever code that depends on a beforeAll() result should be wrapped in before(), after*(), then() or something like that.

**Comment by wangvnn** [comment]
This is the example I have:

void MyBeforeAll()
{
    XYZ();
}

Specify() {

    beforeAll(MyBeforeAll)

    given()
    {
        doABC_ButItNeed_XYZFirst();
        when()
        {
            then()
           {
           }
        }
    }
}

In my test,  I trace them out:

discover tests:
   thead 1: given: doABC_ButItNeed_XYZFirst()  (this could be failed since
it needs XYZ)

run tests:
thead 2: MyBeforeAll()
thread 3: given
thread 3: when
thread 3: then

so to make it working I have a flag:
void MyBeforeAll()
{
    XYZ();
    flag = true;
}

and in the given I did:
given()
{
   if (flag)
   {
   }
}

So it works for now but it is not very nice. I wonder Why do we need to run
some steps of the test without the BeforeAll to discover tests?
I even find out that the BeforeAll was called in a different thread than
the given, when, then which may cause issue as well.
It is good if I can enforce all the steps to be run in 1 single thread.
Maybe I miss some step to setup the configuration, but this is what I got
when tracing all the steps in the console. (print out some text for each
step).


/quang

**Comment by fschwiet** [comment]
Use before(doABC_ButItNeed_XYZFirst) [or is it beforeEach(doABC_ButItNeed_XYZFirst), I forget] to avoid needing the if statement.

**Comment by fschwiet** [comment]
NJasmine does something different than other RSpec like test languages.  It is hard to explain..  Its typical for all tests to run sequentially, sharing variables of local scope.  This has the unfortunate effect of making it easy to leak local variable changes across tests.  NJasmine does not, it uses a new stack of scopes for each test.

**Comment by fschwiet** [comment]
Traditionally with other RSpec like test languages, the test author must be careful to use beforeEach() to ensure it runs before each test, as the beforeAll() behavior is default (though beforeAll() must still be used to prevent expensive setup code to run during test discovery).  In NJasmine this is reversed, as the beforeEach() behavior is usually more appropriate.

**Comment by fschwiet** [comment]
Since each test gets a unique scopes, they cannot have the shared behavior (beforeAll) in their own scope.  Hence, that stuff runs in another thread.

**Comment by wangvnn** [comment]
I actually use NJasmine to write integration test BDD style like CATCH CPP
https://github.com/philsquared/Catch/blob/master/docs/tutorial.md (BDD style section).
Something like this:

USECASE("My Usecase 1")
{
     BeforeAll();  // start App to be tested
     
     given("")
     {
           // common setup code is here
           // ex: create  a network
           when()
           {
                 // scenario 1 path.
                 // ex: add a node
                 then() { // network should have 1 node}
                 and_when() 
                 { 
                      //  scenario 1.1 path 
                      // add another node and connect with the previous node
                      then()
                      {  network should have 2 nodes, and 1 edge }
                 }                
           }

          when() 
          {
               // scenario 2 path....
               then() {}
          }
     }   

     AfterAll();  // shut down tested App 
}

In this style, different scenario paths can share some setup code easily and naturally.
I can do this with NJasmine now with just a bit of custom code.
So I am fine and happy with it :)
I am just curious to know exactly who and why those steps was designed.

Thank you for you help, this tool is awesome.

**Comment by fschwiet** [comment]
I was motived by principle Keep Tests Independent in  "http://xunitpatterns.com/Principles%20of%20Test%20Automation.html#Keep Tests Independent".

**Comment by wangvnn** [comment]
That is a very good rule for TDD.
But nowadays I am not doing strictly TDD.
Indeed in my workflow TDD is the 2nd priority, 1st priority is BDD.
So BDD is the outside loop and TDD is the inside loop.
I use BDD + use case to build the test. I often have this pattern:

BeforeAll

Scenario1: G1 W1 T1
Scenario2: G1 W1 W2 T2
Scenario3: G1 W1 W3 T3
Scenario4: G1 W1 W2 W4 T4
Scenario4: G1 W1 W2 W5 T5

AfterAll

So G1, W1 are reused. In this case I can turn G1 to BeforeEach without
problem.
But it is harder to use BeforeEach for reused W steps.
In NJasmine, the discovery step run both G and W so I have to use the flag
to differentiate between discovery and run time.

Thanks for sharing the motivation behind it.

**Comment by fschwiet** [comment]
I wonder, why is it harder to use beforeEach for the reused W steps?

**Comment by wangvnn** [comment]
Because I have only 1 G step for all scenarios, but each scenario can have
different combinations for the W steps.

My real problem actually is: why the discovery step needs to run the real
code of Given and When but not Then. Is there any way to discover the G/W
steps without really running them.  This also means we double the time to
run the test. I am just curious here, no offense :)

**Comment by fschwiet** [comment]
The discovery step is needed by the various test runners, as their UIs want to show what tests can be run.  If there was a command line runner, it could potentially skip that step (assuming the command-line runner doesn't have a "list steps" function).  Maybe reflection or Roslyn could be used to inspect the code and discover tests without running it... but I'm not hopeful on that.  I don't know how it could work with a data-driven test like:


    for(var i = 0; i < someLimit(); i++) {
        then(“it handles “ + i, function() { });
    }

**Comment by wangvnn** [comment]
Thanks for help me to understand that. I got something very close to what I
wish with NJasmine. So it is not too bad for me.
Thanks a lot for sharing great work.

**Comment by wangvnn** [comment]
In short, the main issue is running a step (given/when) twice (in the discovery and execution) is bad for some cases. 
Eg. the step is required to run once only, or it may be slow also.

**Comment by fschwiet** [comment]
in that case you need to wrap it in beforeAll() or beforeEach(), then it will not run during discovery.
